name: heybuddy
channels:
  - default
  - conda-forge
  - nvidia/label/cuda-12.4
dependencies:
  - cuda-toolkit=12.4.1
  - python=3.10.11
  - pip
  - pip:
    - audiomentations>=0.37
    - click>=8.1
    - datasets>=3.0
    - hf_transfer>=0.1.8
    - librosa>=0.10
    - matplotlib>=3.8
    - onnx>=1.17
    - onnxruntime>=1.18
    - pronouncing>=0.2
    - psutil>=6.0
    - av>=12.2
    - requests>=2.28
    - soundfile>=0.12
    - speechbrain>=1.0
    - tokenizers>=0.20
    - torch>=2.3
    - torch_audiomentations>=0.11
    - torchaudio>=2.3
    - torchmetrics>=1.4
    - tqdm>=4.65
    - wandb>=0.18
    - monotonic_align>=1.0
    - safetensors>=0.4
    - phonemizer>=3.0
    - https://github.com/rhasspy/piper-phonemize/releases/download/v1.1.0/piper_phonemize-1.1.0-cp310-cp310-manylinux_2_28_x86_64.whl
    - --extra-index-url https://download.pytorch.org/whl/cu124
